### ISSUE TITLE
Pure function calls on union receivers crash the verifier

### ISSUE THREAD

**Issue by marcoeilers** [marcoeilers/nagini#117]
The following code should verify, but crashes Nagini:

```
from nagini_contracts.contracts import *
from typing import Union

class A:
    @Pure
    def some_int(self) -> int:
        return 5

class B:
    @Pure
    def some_int(self) -> int:
        return 7

def test_union_function(u: Union[A, B]) -> int:
    Ensures(Result() == 5 or Result() == 7)
    tmp = u.some_int()
```

**Comment by fabiopakk** [comment]
The fix was implemented in branch fabiopakk_pure_functions_on_union, under review.

**Comment by fabiopakk** [comment]
Pull request was approved. I'm closing this issue. The mentioned branch also includes the code above as one of the test cases.

**Comment by fabiopakk** [comment]
Branch renamed to: fabiopakk_issue_117_pure_functions
