### ISSUE TITLE
Imprecise handling of implicit type conversion with union type

### ISSUE THREAD

**Issue by marcoeilers** [marcoeilers/nagini#118]
The following code should verify, but at least one assertion fails:

```
from nagini_contracts.contracts import *
from typing import Union, List

def test_union_function(u: Union[List[int], int]) -> None:
    Requires(Implies(isinstance(u, list), list_pred(u)))
    if not u:
        if isinstance(u, int):
            assert u == 0
        else:
            assert len(u) == 0
```
The problem seems to be that ``if not u`` gets translated to ``if (!object___bool__(u))`` instead of something like ``if (!(isinstance(u, int) ? int___bool__(u) : list___bool__(u)))``. My guess would be that we would have a similar problem in other situations where ``self.get_function_call`` is used internally.

**Comment by fabiopakk** [comment]
Problem analyzed and fixed in branch fabiopakk_implicit_type_conversion_on_union. Pull (and peer-review) requested.

**Comment by fabiopakk** [comment]
Merged.

**Comment by fabiopakk** [comment]
Branch renamed to: fabiopakk_issue_118_implicit_type_conversion
