### ISSUE TITLE
Static field access mistakenly considered

### ISSUE THREAD

**Issue by fabiopakk** [marcoeilers/nagini#119]
The code below `A(5).value` is being considered as static field access. Instead, it should be considered as a regular object field access, because A(5) refers to an instance object, not class A. To reproduce, use the code below.

```
class A:
    def __init__(self, value: int) -> None:
        Ensures(Acc(self.value))
        self.value = value  # type: int

def test() -> None:
    Assert(A(5).value == 5)
```

**Comment by marcoeilers** [comment]
This seems to have been fixed at some point.
