### ISSUE TITLE
"Unsupported type: PartialType" Error

### ISSUE THREAD

**Issue by adh1s** [marcoeilers/nagini#169]
We regularly encountered the Nagini error "Unsupported type: PartialType". An example is below. We were wondering if the authors had any guidance on the reason for this, and potential fixes. Thanks!

**Nagini error raised:** 
```
"""
Not supported: Unsupported type: PartialType (/HumanEval_123.py@23.4)
Translation failed
"""
```

**Code:** 

```
from typing import List

def get_odd_collatz(n: int) -> List[int]:
    """
    Given a positive integer n, return a sorted list that has the odd numbers in collatz sequence.

    The Collatz conjecture is a conjecture in mathematics that concerns a sequence defined
    as follows: start with any positive integer n. Then each term is obtained from the 
    previous term as follows: if the previous term is even, the next term is one half of the 
    previous term. If the previous term is odd, the next term is 3 times the previous
    term plus 1. The conjecture is that no matter what value of n, the sequence will always reach 1.

    Note: 
        1. Collatz(1) is [1].
        2. returned list sorted in increasing order.

    For example:
    get_odd_collatz(5) returns [1, 5] # The collatz sequence for 5 is [5, 16, 8, 4, 2, 1], so the odd numbers are only 1, and 5.
    """


    ans, x = [], n
    while x != 1:
        if x % 2 == 1: ans.append(x)
        x = x // 2 if x % 2 == 0 else x * 3 + 1
    ans.append(1)
    return sorted(ans)
```

**Comment by marcoeilers** [comment]
The issue is that mypy does not infer a proper type for variable ``ans``; it can infer that it is a list, but not the type argument (i.e. that it's a list of integers). Variables that are initialized with empty collections generally need a type annotation for that reason.

So in your example, the fix would be to rewrite it to 
```
...
ans: List[int] = []
x = n
...
```

PR #170 improves the error message for this case.

**Comment by adh1s** [comment]
Thank you for your response and the PR. I have tried this fix and the following error results:

**Comment by marcoeilers** [comment]
My guess is that that's because you're using an old version (e.g. the last official release) of Nagini. I added support for this kind of type hint somewhat recently, so you'll have to install Nagini from source (check out the repository and in the repo directory use ``pip install .``).
