### ISSUE TITLE
Multiset comparison in postconditions

### ISSUE THREAD

**Issue by alex28sh** [marcoeilers/nagini#199]
Hello, is it possible to do a comparison of multisets in postconditions like that: 

```
def sort(init : List[int]) -> List[int]:
   ...
   Ensures(multiset(init) == multiset(Result()))
```

**Comment by alex28sh** [comment]
And also set comparisons 
`set(init) == set(Result())` ?

**Comment by marcoeilers** [comment]
For the first point, yes, there is a function (in Nagini's contract library) ``ToSeq`` that gives you the sequence representation of a standard Python collection, and then there is ``ToMS`` to convert a sequence to a multiset. So for your example, ``ToMS(ToSeq(init)) == ToMS(ToSeq(Result()))``.

There is currently no way to convert to a set, unfortunately.

**Comment by alex28sh** [comment]
> For the first point, yes, there is a function (in Nagini's contract library) `ToSeq` that gives you the sequence representation of a standard Python collection, and then there is `ToMS` to convert a sequence to a multiset. So for your example, `ToMS(ToSeq(init)) == ToMS(ToSeq(Result()))`.
> 
> There is currently no way to convert to a set, unfortunately.

Thank you, that's what I needed!
