### ISSUE TITLE
Logs of Z3-solver

### ISSUE THREAD

**Issue by alex28sh** [marcoeilers/nagini#206]
Hello, now, for debugging and understanding the reasons for some issues we are facing, we are interested in logs produced by Z3 Solver. Is there any way to extract these logs?

Thank you for considering this request. 

Best regards, 
Alex

**Comment by alex28sh** [comment]
Or, maybe, is there any way of printing code, used by Z3 solver?

**Comment by viper-admin** [comment]
Assuming you're using Nagini with the default Viper backend, you can use the command line argument ``--viper-arg=--enableTempDirectory``, and Viper will create a ``tmp`` folder in the current directory that contains ``.smt2`` files that contain all interactions with Z3.

**Comment by marcoeilers** [comment]
Assuming you're using Nagini with the default Viper backend, you can use the command line argument ``--viper-arg=--enableTempDirectory``, and Viper will create a ``tmp`` folder in the current directory that contains ``.smt2`` files that contain all interactions with Z3.
